- name: using default filter
  hosts: localhost
  tasks:
  - name: default value
    vars:
     age: 21
    ansible.builtin.debug:
     msg: "Hi my name is {{name | default('Bhanu')}} and i am {{age}} years old"
  
- name: using lower and upper filter
  hosts: localhost
  vars:
     greet: A very good morning
  tasks:
  - name: uppercase string
    ansible.builtin.debug:
     msg: "Hi, {{greet | upper}}"
 
  - name: lowercase string
    ansible.builtin.debug:
     msg: "Hi, {{greet | lower}}"
