- name: demo on loops
  hosts: localhost
  tasks:
  - name: loops
    ansible.builtin.debug:
     msg: "Hi {{item}}"
    loop: ["bhanu", "sai", "charan"]
    # - bhanu
    # - sai
    # - charan

#- name: install packages by using loops
  