- name: demo on loops
  hosts: localhost
  tasks:
   - name: loops
     ansible.builtin.debug:
      msg: "Hi {{item}}"
     loop: ["bhanu", "sai", "charan"]
    # - bhanu
    # - sai
    # - charan

- name: install packages by using loops
  hosts: localhost
  become: yes
  tasks:
   - name: install software
     ansible.builtin.dnf:
      name: "{{item}}"
      state: present
     loop: ["nodejs", "nginx", "postfix"]

# - name: install packages by using loops
#   hosts: web
#   become: yes
#   tasks:
#   - name: install software
#     ansible.builtin.dnf:
#      name: "{{item.name}}"
#      state: "{{item.state}}"
#     loop: 
#     - {name: mysql, state: absent}
#     - {name: nginx, state: present}
#     - {name: postfix, state: absent}


  