- name: multiplay 
  hosts: localhost
  tasks:
   - name: play1 task1
     ansible.builtin.debug:
      msg: "This is play1 and task1"

- name: multiplay
  hosts: web
  tasks:
   - name: play2 task1
     ansible.builtin.debug:
      msg: "This is play2 and task1"
