- name: install the nginx server
  hosts: web
  become: yes
  tasks: 
  - name: installing the nginx
    dnf.builtin.package:
      name: nginx
      state: present
  - name: start nginx
    dnf.builtin.service:
      name: nginx
      state: started
      enables: yes

    
